// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shiptech.Infrastructure.Data;

#nullable disable

namespace Shiptech.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shiptech.Domain.Entities.Assortment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(26)")
                        .HasColumnName("Id");

                    b.Property<short?>("Addition")
                        .HasColumnType("smallint")
                        .HasColumnName("Addition");

                    b.Property<short>("AssemblyLength")
                        .HasColumnType("smallint")
                        .HasColumnName("AssemblyLength");

                    b.Property<short>("AssemblyQuantity")
                        .HasColumnType("smallint")
                        .HasColumnName("AssemblyQuantity");

                    b.Property<double>("AssemblyWeight")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("AssemblyWeight");

                    b.Property<string>("AssortmentDictionaryId")
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Comment")
                        .HasColumnType("varchar")
                        .HasColumnName("Comment");

                    b.Property<short?>("D15I")
                        .HasColumnType("smallint")
                        .HasColumnName("D15I");

                    b.Property<short?>("D15II")
                        .HasColumnType("smallint")
                        .HasColumnName("D15II");

                    b.Property<short?>("D1I")
                        .HasColumnType("smallint")
                        .HasColumnName("D1I");

                    b.Property<short?>("D1II")
                        .HasColumnType("smallint")
                        .HasColumnName("D1II");

                    b.Property<short?>("DrawingLength")
                        .HasColumnType("smallint")
                        .HasColumnName("DrawingLength");

                    b.Property<string>("IsoId")
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Name");

                    b.Property<char>("Position")
                        .HasColumnType("char(1)")
                        .HasColumnName("Position");

                    b.Property<short>("PrefabricationLength")
                        .HasColumnType("smallint")
                        .HasColumnName("PrefabricationLength");

                    b.Property<short>("PrefabricationQuantity")
                        .HasColumnType("smallint")
                        .HasColumnName("PrefabricationQuantity");

                    b.Property<double>("PrefabricationWeight")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("PrefabricationWeight");

                    b.Property<char?>("Stage")
                        .HasColumnType("char(1)")
                        .HasColumnName("Stage");

                    b.Property<short?>("TechnologicalAddition")
                        .HasColumnType("smallint")
                        .HasColumnName("TechnologicalAddition");

                    b.HasKey("Id");

                    b.HasIndex("AssortmentDictionaryId");

                    b.HasIndex("IsoId");

                    b.ToTable("Assortments", (string)null);
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.AssortmentDictionary", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(26)")
                        .HasColumnName("Id");

                    b.Property<double?>("Amount")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("Amount");

                    b.Property<string>("Comment")
                        .HasColumnType("varchar")
                        .HasColumnName("Comment");

                    b.Property<string>("DN1")
                        .HasColumnType("varchar")
                        .HasColumnName("DN1");

                    b.Property<string>("DN2")
                        .HasColumnType("varchar")
                        .HasColumnName("DN2");

                    b.Property<string>("Distinguishing")
                        .IsRequired()
                        .HasColumnType("char(22)")
                        .HasColumnName("Distinguishing");

                    b.Property<string>("Kind")
                        .HasColumnType("varchar")
                        .HasColumnName("Kind");

                    b.Property<short?>("Length")
                        .HasColumnType("smallint")
                        .HasColumnName("Length");

                    b.Property<string>("Material")
                        .HasColumnType("varchar")
                        .HasColumnName("Material");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Number");

                    b.Property<string>("RO")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("RO");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .HasColumnName("Unit");

                    b.Property<double?>("Weight")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("Weight");

                    b.HasKey("Id");

                    b.ToTable("AssortmentDictionary", (string)null);
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.ChemicalProcess", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(26)")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("ChemicalProcessCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("ChemicalProcessName");

                    b.HasKey("Id");

                    b.ToTable("ChemicalProcesses", (string)null);
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.Drawing", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(26)")
                        .HasColumnName("Id");

                    b.Property<string>("Block")
                        .HasColumnType("char(3)")
                        .HasColumnName("Block");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreationDate");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Author");

                    b.Property<string>("Lot")
                        .HasColumnType("char(3)")
                        .HasColumnName("Lot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Number");

                    b.Property<char>("Revision")
                        .HasColumnType("char(1)")
                        .HasColumnName("Revision");

                    b.Property<string[]>("Section")
                        .HasColumnType("text[]")
                        .HasColumnName("Section");

                    b.Property<string>("ShipId")
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Stage")
                        .HasColumnType("char(3)")
                        .HasColumnName("Stage");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("Drawings", (string)null);
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.Iso", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(26)")
                        .HasColumnName("Id");

                    b.Property<string>("Atest")
                        .HasColumnType("varchar")
                        .HasColumnName("Atest");

                    b.Property<string>("ChemicalProcessId")
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("char(6)")
                        .HasColumnName("Class");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreationDate");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Author");

                    b.Property<string>("DrawingId")
                        .HasColumnType("varchar(26)");

                    b.Property<DateOnly?>("KzmDate")
                        .HasColumnType("date")
                        .HasColumnName("KzmDate");

                    b.Property<string>("KzmNumber")
                        .HasColumnType("char(6)")
                        .HasColumnName("KzmNumber");

                    b.Property<string>("Nameplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Number");

                    b.Property<char>("Revision")
                        .HasColumnType("char(1)")
                        .HasColumnName("Revision");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("System");

                    b.HasKey("Id");

                    b.HasIndex("ChemicalProcessId");

                    b.HasIndex("DrawingId");

                    b.ToTable("Isos", (string)null);
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.Ship", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(26)")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Code");

                    b.Property<string>("Orderer")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Orderer");

                    b.HasKey("Id");

                    b.ToTable("Ships", (string)null);
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.Assortment", b =>
                {
                    b.HasOne("Shiptech.Domain.Entities.AssortmentDictionary", "AssortmentDictionary")
                        .WithMany("Assortments")
                        .HasForeignKey("AssortmentDictionaryId");

                    b.HasOne("Shiptech.Domain.Entities.Iso", "Iso")
                        .WithMany("Assortments")
                        .HasForeignKey("IsoId");

                    b.Navigation("AssortmentDictionary");

                    b.Navigation("Iso");
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.Drawing", b =>
                {
                    b.HasOne("Shiptech.Domain.Entities.Ship", "Ship")
                        .WithMany("Drawings")
                        .HasForeignKey("ShipId");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.Iso", b =>
                {
                    b.HasOne("Shiptech.Domain.Entities.ChemicalProcess", "ChemicalProcess")
                        .WithMany("Isos")
                        .HasForeignKey("ChemicalProcessId");

                    b.HasOne("Shiptech.Domain.Entities.Drawing", "Drawing")
                        .WithMany("Isos")
                        .HasForeignKey("DrawingId");

                    b.Navigation("ChemicalProcess");

                    b.Navigation("Drawing");
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.AssortmentDictionary", b =>
                {
                    b.Navigation("Assortments");
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.ChemicalProcess", b =>
                {
                    b.Navigation("Isos");
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.Drawing", b =>
                {
                    b.Navigation("Isos");
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.Iso", b =>
                {
                    b.Navigation("Assortments");
                });

            modelBuilder.Entity("Shiptech.Domain.Entities.Ship", b =>
                {
                    b.Navigation("Drawings");
                });
#pragma warning restore 612, 618
        }
    }
}
