volumes:
  postgres:

services:
  api:
    container_name: shiptech_api
    image: shiptech-api
    build:
      context: .
      dockerfile: Shiptech.Api/Dockerfile
  db:
    container_name: shiptech_db
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: shiptech
      POSTGRES_USER: ${SHIPTECH_DATABASE_USER}
      POSTGRES_PASSWORD: ${SHIPTECH_DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
