// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shiptech.Infrastructure.EF.Contexts;

#nullable disable

namespace Shiptech.Infrastructure.EF.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20240324124628_InitCreateTables")]
    partial class InitCreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.AssortmentDictionaryReadModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<double>("Amount")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("Amount");

                    b.Property<string>("Comment")
                        .HasColumnType("varchar")
                        .HasColumnName("Comment");

                    b.Property<string>("Distinguishing")
                        .IsRequired()
                        .HasColumnType("char(6)")
                        .HasColumnName("Distinguishing");

                    b.Property<string>("Kind")
                        .HasColumnType("varchar")
                        .HasColumnName("Kind");

                    b.Property<short?>("Length")
                        .HasColumnType("smallint")
                        .HasColumnName("Length");

                    b.Property<string>("Material")
                        .HasColumnType("varchar")
                        .HasColumnName("Material");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Name");

                    b.Property<string>("RO")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("RO");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .HasColumnName("Unit");

                    b.Property<double>("Weight")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("Weight");

                    b.HasKey("Id");

                    b.ToTable("AssortmentDictionary", (string)null);
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.AssortmentReadModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<short?>("Addition")
                        .HasColumnType("smallint")
                        .HasColumnName("Addition");

                    b.Property<short>("AssemblyLength")
                        .HasColumnType("smallint")
                        .HasColumnName("AssemblyLength");

                    b.Property<short>("AssemblyQuantity")
                        .HasColumnType("smallint")
                        .HasColumnName("AssemblyQuantity");

                    b.Property<double>("AssemblyWeight")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("AssemblyWeight");

                    b.Property<string>("AssortmentDictionaryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("varchar")
                        .HasColumnName("Comment");

                    b.Property<short?>("D15I")
                        .HasColumnType("smallint")
                        .HasColumnName("D15I");

                    b.Property<short?>("D15II")
                        .HasColumnType("smallint")
                        .HasColumnName("D15II");

                    b.Property<short?>("D1I")
                        .HasColumnType("smallint")
                        .HasColumnName("D1I");

                    b.Property<short?>("D1II")
                        .HasColumnType("smallint")
                        .HasColumnName("D1II");

                    b.Property<short?>("DrawingLength")
                        .HasColumnType("smallint")
                        .HasColumnName("DrawingLength");

                    b.Property<string>("IsoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("Position")
                        .HasColumnType("char(1)")
                        .HasColumnName("Position");

                    b.Property<short>("PrefabricationLength")
                        .HasColumnType("smallint")
                        .HasColumnName("PrefabricationLength");

                    b.Property<short>("PrefabricationQuantity")
                        .HasColumnType("smallint")
                        .HasColumnName("PrefabricationQuantity");

                    b.Property<double>("PrefabricationWeight")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("PrefabricationWeight");

                    b.Property<string>("Stage")
                        .HasColumnType("char(1)")
                        .HasColumnName("Stage");

                    b.Property<short?>("TechnologicalAddition")
                        .HasColumnType("smallint")
                        .HasColumnName("TechnologicalAddition");

                    b.HasKey("Id");

                    b.HasIndex("AssortmentDictionaryId");

                    b.HasIndex("IsoId");

                    b.ToTable("Assortments", (string)null);
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.ChemicalProcessReadModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<string>("ChemicalProcessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChemicalProcesses", (string)null);
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.DrawingReadModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Author");

                    b.Property<string>("Block")
                        .HasColumnType("char(3)")
                        .HasColumnName("Block");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreationDate");

                    b.Property<char>("DrawingRevision")
                        .HasColumnType("char(1)")
                        .HasColumnName("DrawingRevision");

                    b.Property<string>("Lot")
                        .HasColumnType("char(3)")
                        .HasColumnName("Lot");

                    b.Property<string>("Section")
                        .HasColumnType("char(4)")
                        .HasColumnName("Section");

                    b.Property<string>("ShipId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .HasColumnType("char(3)")
                        .HasColumnName("Stage");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("Drawings", (string)null);
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.IsoReadModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<string>("Atest")
                        .HasColumnType("varchar")
                        .HasColumnName("Atest");

                    b.Property<string>("ChemicalProcessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("char(6)")
                        .HasColumnName("Class");

                    b.Property<string>("DrawingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("IsoRevision")
                        .HasColumnType("char(1)")
                        .HasColumnName("DrawingRevision");

                    b.Property<DateTime?>("KzmDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("KzmDate");

                    b.Property<string>("KzmNumber")
                        .HasColumnType("char(6)")
                        .HasColumnName("KzmNumber");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("System");

                    b.HasKey("Id");

                    b.HasIndex("ChemicalProcessId");

                    b.HasIndex("DrawingId");

                    b.ToTable("Isos", (string)null);
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.ShipReadModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<string>("Orderer")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Orderer");

                    b.HasKey("Id");

                    b.ToTable("Ships", (string)null);
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.AssortmentReadModel", b =>
                {
                    b.HasOne("Shiptech.Infrastructure.EF.Models.AssortmentDictionaryReadModel", "AssortmentDictionary")
                        .WithMany("Assortments")
                        .HasForeignKey("AssortmentDictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiptech.Infrastructure.EF.Models.IsoReadModel", "Iso")
                        .WithMany("Assortments")
                        .HasForeignKey("IsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssortmentDictionary");

                    b.Navigation("Iso");
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.DrawingReadModel", b =>
                {
                    b.HasOne("Shiptech.Infrastructure.EF.Models.ShipReadModel", "Ship")
                        .WithMany("Drawings")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.IsoReadModel", b =>
                {
                    b.HasOne("Shiptech.Infrastructure.EF.Models.ChemicalProcessReadModel", "ChemicalProcess")
                        .WithMany("Isos")
                        .HasForeignKey("ChemicalProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiptech.Infrastructure.EF.Models.DrawingReadModel", "Drawing")
                        .WithMany("Isos")
                        .HasForeignKey("DrawingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChemicalProcess");

                    b.Navigation("Drawing");
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.AssortmentDictionaryReadModel", b =>
                {
                    b.Navigation("Assortments");
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.ChemicalProcessReadModel", b =>
                {
                    b.Navigation("Isos");
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.DrawingReadModel", b =>
                {
                    b.Navigation("Isos");
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.IsoReadModel", b =>
                {
                    b.Navigation("Assortments");
                });

            modelBuilder.Entity("Shiptech.Infrastructure.EF.Models.ShipReadModel", b =>
                {
                    b.Navigation("Drawings");
                });
#pragma warning restore 612, 618
        }
    }
}
